# Generated by Django 6.0.1 on 2026-01-16 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NewWord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Word', models.CharField(max_length=100)),
                ('Meaning', models.TextField()),
                ('DeepMeaing', models.TextField()),
                ('ExampleSentence', models.TextField()),
                ('Image', models.ImageField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Quickadd',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Word', models.CharField(max_length=100)),
                ('meaning', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='WordMastery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Word', models.CharField(max_length=100)),
                ('Meaning', models.TextField()),
                ('DeepMeaing', models.TextField()),
                ('ExampleSentence', models.TextField()),
                ('Image', models.ImageField(upload_to='')),
            ],
        ),
    ]
